# Generated by Django 3.2.22 on 2023-11-22 13:15

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_auto_20231121_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
