# Generated by Django 3.2.22 on 2023-12-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0004_order_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineitem",
            name="product_weight",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
