# Generated by Django 3.2.22 on 2023-12-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0005_orderlineitem_product_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="product_weight",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
