# Generated by Django 3.2.22 on 2023-12-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0006_alter_orderlineitem_product_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
