# Generated by Django 3.2.22 on 2023-12-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_auto_20231113_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_weight",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
